(() => {
  'use strict';
  const config = window.PV_CONFIG || {};
  const NEWS_CONTROL_URL = './control.html';
  const CHECKOUT_URL = './checkout.html';
  const qs = (s, r = document) => r.querySelector(s);
  const qsa = (s, r = document) => [...r.querySelectorAll(s)];
  const fmtDate = value => value ? new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)) : '—';
  const initials = name => (name || 'PontoView').split(/\s+/).filter(Boolean).slice(0,2).map(v=>v[0]).join('').toUpperCase();
  let client=null,currentUser=null,accessActive=false;
  const authScreen=qs('#authScreen'),studioShell=qs('#studioShell');
  function initClient(){if(window.supabase?.createClient&&config.supabaseUrl&&config.supabaseKey){client=window.supabase.createClient(config.supabaseUrl,config.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}}
  function showApp(){authScreen.hidden=true;studioShell.hidden=false}function showAuth(){authScreen.hidden=false;studioShell.hidden=true}
  function applyUser(user,p=null){const email=user?.email||'conta@pontoview.com.br';const name=p?.full_name||user?.user_metadata?.full_name||email.split('@')[0].replace(/[._-]/g,' ')||'Conta PontoView';const init=initials(name);currentUser=user;qs('#userName').textContent=name;qs('#userEmail').textContent=email;qs('#userInitials').textContent=init;qs('#welcomeTitle').textContent=`Olá, ${name.split(' ')[0]}.`;qs('#accountName').textContent=name;qs('#accountEmail').textContent=email;qs('#accountAvatar').textContent=init;qs('#accountNameRow').textContent=name;qs('#accountEmailRow').textContent=email}
  function applyAccess(active,sub=null){accessActive=!!active;const chip=qs('#subscriptionChip');chip.classList.remove('is-checking','is-active','is-locked');chip.classList.add(accessActive?'is-active':'is-locked');chip.querySelector('span').textContent=accessActive?'Studio ativo':'Assinatura necessária';qs('#paywallBanner').hidden=accessActive;qs('#libraryAccessLabel').textContent=accessActive?'Sua assinatura está ativa':'Assine para liberar os controles';qs('#billingStatus').textContent=accessActive?'ATIVA':'INATIVA';qs('#billingStatus').className=`pv-billing-status ${accessActive?'active':'locked'}`;qs('#billingStarted').textContent=fmtDate(sub?.started_at);qs('#billingExpires').textContent=fmtDate(sub?.expires_at);qsa('[data-product="news_overlay"]').forEach(card=>card.classList.toggle('is-locked',!accessActive));qsa('[data-open-product="news_overlay"]').forEach(btn=>btn.textContent=accessActive?'Abrir overlay':'Assinar para usar');qsa('[data-action="subscribe"]').forEach(btn=>btn.textContent=accessActive?'Gerenciar assinatura':'Assinar por R$ 59/mês')}
  function setView(view){qsa('[data-view-panel]').forEach(p=>p.classList.toggle('active',p.dataset.viewPanel===view));qsa('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={home:'Início',library:'Overlays',billing:'Assinatura',account:'Minha conta'};qs('#topbarTitle').textContent=titles[view]||'Meu Studio';window.scrollTo({top:0,behavior:'smooth'});qs('.pv-sidebar')?.classList.remove('open')}
  function openModal(title,copy){qs('#modalTitle').textContent=title;qs('#modalCopy').textContent=copy;qs('#noticeModal').hidden=false}
  function bindUI(){qsa('[data-view]').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.view)));qsa('[data-go-view]').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.goView)));qs('#accountMenuButton')?.addEventListener('click',()=>setView('account'));qs('#sidebarToggle')?.addEventListener('click',()=>qs('.pv-sidebar')?.classList.toggle('open'));qsa('[data-close-modal]').forEach(btn=>btn.addEventListener('click',()=>qs('#noticeModal').hidden=true));qs('#noticeModal')?.addEventListener('click',e=>{if(e.target===qs('#noticeModal'))qs('#noticeModal').hidden=true});qsa('[data-action="subscribe"]').forEach(btn=>btn.addEventListener('click',()=>location.href=CHECKOUT_URL));qsa('[data-action="billing-help"]').forEach(btn=>btn.addEventListener('click',()=>location.href='mailto:suporte@pontoview.com.br?subject=Ajuda%20com%20cobrança%20PontoView%20Studio'));qsa('[data-action="password-reset"]').forEach(btn=>btn.addEventListener('click',async()=>{if(!client||!currentUser?.email)return;const{error}=await client.auth.resetPasswordForEmail(currentUser.email,{redirectTo:`${location.origin}/studio.html`});openModal('Alterar senha',error?error.message:'Enviamos as instruções de troca de senha para o seu e-mail.')}));qsa('[data-open-product]').forEach(btn=>btn.addEventListener('click',()=>{if(!accessActive){location.href=CHECKOUT_URL;return}if(btn.dataset.openProduct==='news_overlay')location.href=NEWS_CONTROL_URL}));qs('#logoutButton')?.addEventListener('click',async()=>{if(client)await client.auth.signOut();showAuth()})}
  async function loadAccount(user){const[{data:p},{data:sub,error:subError}]=await Promise.all([client.from('profiles').select('full_name,email,avatar_url').eq('id',user.id).maybeSingle(),client.from('subscriptions').select('product,active,started_at,expires_at,created_at').eq('user_id',user.id).eq('product',config.product||'news_overlay').eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle()]);applyUser(user,p||null);if(subError)console.warn('Não foi possível consultar a assinatura:',subError.message);const valid=!!(sub?.active&&(!sub.expires_at||new Date(sub.expires_at)>new Date()));applyAccess(valid,valid?sub:null)}
  async function authenticate(email,password){if(!client)throw new Error('Serviço de autenticação indisponível.');const{data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;await loadAccount(data.user);showApp()}
  function bindAuth(){qs('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=qs('#loginMessage');msg.textContent='Entrando…';msg.className='pv-form-message';try{await authenticate(qs('#loginEmail').value.trim(),qs('#loginPassword').value)}catch(err){msg.textContent=err?.message||'Não foi possível entrar.';msg.className='pv-form-message error'}});qs('#forgotPassword')?.addEventListener('click',async()=>{const email=qs('#loginEmail').value.trim(),msg=qs('#loginMessage');if(!email){msg.textContent='Digite seu e-mail primeiro.';msg.className='pv-form-message error';return}if(!client)return;const{error}=await client.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/studio.html`});msg.textContent=error?error.message:'Confira seu e-mail para continuar.';msg.className=`pv-form-message ${error?'error':'ok'}`});qs('#createAccountButton')?.addEventListener('click',()=>location.href='./index.html?cadastro=1')}
  async function boot(){initClient();bindUI();bindAuth();if(!client){showAuth();return}const{data:{session}}=await client.auth.getSession();if(session?.user){showApp();await loadAccount(session.user)}else showAuth();client.auth.onAuthStateChange(async(_event,sessionNow)=>{if(sessionNow?.user){showApp();await loadAccount(sessionNow.user)}else showAuth()})}boot();
})();